# [[pages]]
# path = "./streamlit_pages/pages/analytics_page.py"
# name = "ĞĞ½Ğ°Ğ»Ğ¸Ñ‚Ğ¸ĞºĞ°"
# icon = "ğŸ“Š"

[[pages]]
path = "./streamlit_pages/pages/prediciton_page.py"
name = "ĞŸÑ€Ğ¾Ğ³Ğ½Ğ¾Ğ· Ñ†ĞµĞ½Ñ‹"
icon = "ğŸ“ˆ"
